version: "2"
engines:
  fixme:
    enabled: true
  hlint:
    enabled: true
ratings:
  paths: 
    - "Calculator/**.hs"
exclude_patterns:
 - "**/AlexLexer.hs"
 - "**/HappyParser.hs"
 - "telegram-api-0.7.2.0/**"
 - "telegram-bot-simple-0.2.0/**"
