sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  
  - ghc: 8.4.4
    env: GHCVER='8.4.3' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - cabal-install-head

  - ghc: 8.6.1
    env: GHCVER='8.6.1' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.1
        - cabal-install-head

  - ghc: 8.4.4
    env: GHCVER='8.4.3' STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.6.1
    env: GHCVER='8.6.1' STACK_YAML="$TRAVIS_BUILD_DIR/stack-$GHCVER.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
      echo $PATH
      cabal new-update
      cabal new-build Calculator
    else
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"
      travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack --version
      stack setup --no-terminal --install-cabal 2.2.0.1
      stack ghc -- --version
      stack build --only-dependencies --no-terminal
    fi
script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal exec Calculator -- -t
    else
      stack exec Calculator -- -t
    fi

notifications:  
  email: 
    - pitongogi@gmail.com