sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$TRAVIS_BUILD_DIR/dist-newstyle"

matrix:
  include:
  
  - ghc: 8.8.4
    env: GHCVER='8.8.4' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.8.4
        - cabal-install-head

install:
  - |
    export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
    echo $PATH
    cabal new-update
    cabal new-build Calculator --enable-tests
script:
  - |
    cabal new-test Calculator --enable-tests --test-show-details=streaming

notifications:  
  email: 
    - pitongogi@gmail.com
