version: "2.1"

env: &env
    environment:
      LC_ALL: "C.UTF-8"
    docker:
      - image: fpco/stack-build:lts-13

#-----------------------------------------------------------------------------
# Common utility stuff, not to be modified usually
#-----------------------------------------------------------------------------

preinstall: &preinstall
  run: |
      echo 'export PATH=/opt/cabal/bin:/opt/ghc/bin:$PATH' >> $BASH_ENV
      source $BASH_ENV
      apt-get update

restore: &restore
  # Needs to happen after installing ca-certificates
  restore_cache:
    key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}

save: &save
  save_cache:
      key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
      paths:
        - ~/.cabal
        - ~/.ghc
        - ~/.local
        - ~/.stack

commands:
  cabal_build:
    parameters:
      ghcversion:
        type: string
    steps:
      - checkout
      - *preinstall
      - *restore
      - run:
          name: install cabal
          command: apt-get install -y cabal-install-2.4
      - run:
          name: install ghc
          command: |
            apt-get install -y ghc-<< parameters.ghcversion >>
      - run:
          name: build and test project
          command: |
            set -e
            cabal v2-update
            cabal v2-build -w ghc-<< parameters.ghcversion >> -j2 --disable-optimization --dependencies-only --enable-tests --enable-benchmarks
            cabal v2-build -w ghc-<< parameters.ghcversion >> -j2 --disable-optimization --enable-tests --enable-benchmarks 2>build.log
            cat build.log
            cabal v2-test -w ghc-<< parameters.ghcversion >> -j2 --disable-optimization --enable-tests
      - *save

#-----------------------------------------------------------------------------
# Build matrix
#-----------------------------------------------------------------------------

jobs:
  cabal-ghc-8_6_5:
      <<: *env
      steps:
          - cabal_build:
              ghcversion: 8.6.5

workflows:
  version: "2.1"
  build:
    jobs:
      - cabal-ghc-8_6_5
